export const COUNTRY_NAME_BY_CODE: Record<string, string> = {
  ALG: 'Algérie',
  ARG: 'Argentine',
  AUS: 'Australie',
  AUT: 'Autriche',
  BEL: 'Belgique',
  BIH: 'Bosnie-Herzégovine',
  BRA: 'Brésil',
  CAN: 'Canada',
  CHI: 'Chili',
  CHN: 'Chine',
  CMR: 'Cameroun',
  COD: 'RD Congo',
  COL: 'Colombie',
  CPV: 'Cap-Vert',
  CRO: 'Croatie',
  CUW: 'Curaçao',
  CIV: 'Côte d’Ivoire',
  CZE: 'Tchéquie',
  DEN: 'Danemark',
  EGY: 'Égypte',
  ENG: 'Angleterre',
  ESP: 'Espagne',
  ECU: 'Équateur',
  FRA: 'France',
  GER: 'Allemagne',
  GHA: 'Ghana',
  GRE: 'Grèce',
  HAI: 'Haïti',
  IRN: 'Iran',
  IRQ: 'Irak',
  ITA: 'Italie',
  JOR: 'Jordanie',
  JPN: 'Japon',
  KOR: 'Corée du Sud',
  KSA: 'Arabie saoudite',
  MAR: 'Maroc',
  MEX: 'Mexique',
  NED: 'Pays-Bas',
  NGA: 'Nigeria',
  NOR: 'Norvège',
  NZL: 'Nouvelle-Zélande',
  PAN: 'Panama',
  PAR: 'Paraguay',
  POL: 'Pologne',
  POR: 'Portugal',
  QAT: 'Qatar',
  RSA: 'Afrique du Sud',
  SEN: 'Sénégal',
  SCO: 'Écosse',
  SUI: 'Suisse',
  SWE: 'Suède',
  TUN: 'Tunisie',
  TUR: 'Turquie',
  UKR: 'Ukraine',
  URU: 'Uruguay',
  USA: 'États-Unis',
  UZB: 'Ouzbékistan',
};

export const COUNTRY_ALIASES_BY_CODE: Record<string, string[]> = {
  ALG: ['Algeria', 'Algérie', 'Algerie', 'DZ'],
  ARG: ['Argentina', 'Argentine', 'AR'],
  AUS: ['Australia', 'Australie', 'AU'],
  AUT: ['Austria', 'Autriche', 'AT'],
  BEL: ['Belgium', 'Belgique', 'BE'],
  BIH: ['Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Bosnie Herzegovine', 'BA'],
  BRA: ['Brazil', 'Brasil', 'Brésil', 'Bresil', 'BR'],
  CAN: ['Canada', 'CA'],
  CHI: ['Chile', 'Chili'],
  CHN: ['China', 'Chine', 'CN'],
  CMR: ['Cameroon', 'Cameroun', 'CM'],
  COD: ['DR Congo', 'RD Congo', 'Democratic Republic of the Congo', 'Congo DR', 'CD'],
  COL: ['Colombia', 'Colombie', 'CO'],
  CPV: ['Cape Verde', 'Cap-Vert', 'Cabo Verde', 'CV'],
  CRO: ['Croatia', 'Croatie', 'HR'],
  CUW: ['Curacao', 'Curaçao', 'Curacao', 'CW'],
  CIV: ['Ivory Coast', 'Côte d’Ivoire', "Cote d'Ivoire", 'Cote d Ivoire', 'CI'],
  CZE: ['Czech Republic', 'Czechia', 'Tchéquie', 'Tchequie', 'CZ'],
  DEN: ['Denmark', 'Danemark', 'DK'],
  EGY: ['Egypt', 'Égypte', 'Egypte', 'EG'],
  ECU: ['Ecuador', 'Équateur', 'Equateur', 'EC'],
  ENG: ['England', 'Angleterre', 'GB-ENG', 'EN'],
  ESP: ['Spain', 'Espagne', 'ES'],
  FRA: ['France', 'FR'],
  GER: ['Germany', 'Deutschland', 'Allemagne', 'DE', 'DEU'],
  GHA: ['Ghana', 'GH'],
  GRE: ['Greece', 'Grèce', 'Grece', 'GR'],
  HAI: ['Haiti', 'Haïti', 'Haiti', 'HT'],
  IRN: ['Iran', 'IR'],
  IRQ: ['Iraq', 'Irak', 'IQ'],
  ITA: ['Italy', 'Italia', 'Italie', 'IT'],
  JOR: ['Jordan', 'Jordanie', 'JO'],
  JPN: ['Japan', 'Japon', 'JP'],
  KOR: ['Korea Republic', 'South Korea', 'Korea', 'Corée du Sud', 'Coree du Sud', 'KR'],
  KSA: ['Saudi Arabia', 'Arabie saoudite', 'Saudi', 'SA'],
  MAR: ['Morocco', 'Maroc', 'MA'],
  MEX: ['Mexico', 'Mexique', 'MX'],
  NED: ['Netherlands', 'Holland', 'Nederland', 'Pays-Bas', 'NL'],
  NGA: ['Nigeria', 'NG'],
  NOR: ['Norway', 'Norvège', 'Norvege', 'NO'],
  NZL: ['New Zealand', 'Nouvelle-Zélande', 'Nouvelle Zelande', 'NZ'],
  PAN: ['Panama', 'PA'],
  PAR: ['Paraguay', 'PY'],
  POL: ['Poland', 'Pologne'],
  POR: ['Portugal', 'PT'],
  QAT: ['Qatar', 'QA'],
  RSA: ['South Africa', 'Afrique du Sud', 'ZA', 'RSA'],
  SEN: ['Senegal', 'Sénégal', 'Senegal', 'SN'],
  SCO: ['Scotland', 'Écosse', 'Ecosse', 'GB-SCT'],
  SUI: ['Switzerland', 'Suisse', 'CH', 'SUI'],
  SWE: ['Sweden', 'Suède', 'Suede', 'SE'],
  TUN: ['Tunisia', 'Tunisie', 'TN'],
  TUR: ['Turkey', 'Türkiye', 'Turquie', 'TR'],
  UKR: ['Ukraine', 'UA'],
  URU: ['Uruguay', 'UY'],
  USA: ['United States', 'United States of America', 'États-Unis', 'Etats-Unis', 'US'],
  UZB: ['Uzbekistan', 'Ouzbékistan', 'Ouzbekistan', 'UZ'],
};

export const COUNTRY_FLAG_FILE_BY_CODE: Record<string, string> = {
  ALG: 'dz.svg',
  ARG: 'ar.webp',
  AUS: 'au.svg',
  AUT: 'at.svg',
  BEL: 'be.svg',
  BIH: 'ba.svg',
  BRA: 'br.webp',
  CAN: 'ca.webp',
  CHI: 'cl.svg',
  CHN: 'cn.svg',
  CMR: 'cm.svg',
  COD: 'cd.svg',
  COL: 'co.svg',
  CPV: 'cv.svg',
  CRO: 'hr.svg',
  CUW: 'cw.svg',
  CIV: 'ci.svg',
  CZE: 'cz.svg',
  DEN: 'dk.svg',
  EGY: 'eg.svg',
  ECU: 'ec.svg',
  ENG: 'gb-eng.svg',
  ESP: 'es.webp',
  FRA: 'fr.webp',
  GER: 'de.webp',
  GHA: 'gh.svg',
  GRE: 'gr.svg',
  HAI: 'ht.svg',
  IRN: 'ir.svg',
  IRQ: 'iq.svg',
  ITA: 'it.svg',
  JOR: 'jo.svg',
  JPN: 'jp.webp',
  KOR: 'kr.svg',
  KSA: 'sa.svg',
  MAR: 'ma.webp',
  MEX: 'mx.webp',
  NED: 'nl.svg',
  NGA: 'ng.svg',
  NOR: 'no.svg',
  NZL: 'nz.svg',
  PAN: 'pa.svg',
  PAR: 'py.svg',
  POL: 'pl.svg',
  POR: 'pt.webp',
  QAT: 'qa.svg',
  RSA: 'za.svg',
  SEN: 'sn.webp',
  SCO: 'gb-sct.svg',
  SUI: 'ch.svg',
  SWE: 'se.svg',
  TUN: 'tn.svg',
  TUR: 'tr.svg',
  UKR: 'ua.svg',
  URU: 'uy.svg',
  USA: 'us.webp',
  UZB: 'uz.svg',
};

export const getCountryFlagUrl = (countryCode?: string | null): string | undefined => {
  if (!countryCode) return undefined;
  const file = COUNTRY_FLAG_FILE_BY_CODE[countryCode.toUpperCase()];
  return file ? `${import.meta.env.BASE_URL}flags/${file}` : undefined;
};

export const getCountryDisplayName = (countryCode?: string | null): string | undefined => {
  if (!countryCode) return undefined;
  return COUNTRY_NAME_BY_CODE[countryCode.toUpperCase()];
};
